sudo: required
language: python
python:
  - '3.4'
  - '3.6'
install:
  - pip install -r requirements.txt
  - pip install coverage
script: coverage run --include=pymkm.py tests.py
after_success: coverage report