sudo: required
language: python
virtualenv:
  system_site_packages: true
python:
  - '3.4'
  - '3.6'
install:
  - pip install -r requirements.txt
  - pip install coverage
script: coverage run python -m unittest
after_success: coverage report